/* ======================================
   MASS EFFECT WORLD MODEL – FULL KERNEL v2.0
   Data-Driven Scalable World Injection
   ====================================== */

// ---------- WORLD DATA (DATA-DRIVEN STRUCTURE) ----------
// Each entry contains the lore text and an array of keyword triggers with their weights.

var WORLD = {
  // === PHYSICS CORE ===
  physics_eezo_properties: {
    text: "Element Zero (Eezo) is created when matter is exposed to supernova-level forces, altering atomic structure to produce a mass effect field when electrically stimulated. Eezo is inert until energized. Field strength scales with applied current and volume of material. Large-scale industrial extraction requires heavy radiation shielding and autonomous robotics due to neutron-star proximity mining conditions.",
    triggers: [{ word: "eezo", weight: 2 }, { word: "supernova", weight: 1 }]
  },
  physics_mass_field_dynamics: {
    text: "Mass effect fields alter local mass-energy relationships. Negative current lowers effective mass, increasing attainable velocity without relativistic increase. Positive current increases effective mass, enabling artificial gravity and kinetic barriers. Field geometry is shaped by emitter arrays and core configuration.",
    triggers: [{ word: "mass field", weight: 2 }, { word: "positive current", weight: 1 }, { word: "negative current", weight: 1 }]
  },
  physics_ftl_drive_mechanics: {
    text: "FTL travel relies on a sustained low-mass envelope generated by a drive core. The ship’s inertia is reduced rather than classical acceleration exceeding c. Heat and static buildup accumulate in the core; drives must discharge periodically (~50 hours typical) at specialized facilities, planetary magnetospheres, or gas giants. Failure to discharge causes catastrophic core venting.",
    triggers: [{ word: "ftl", weight: 2 }, { word: "drive core", weight: 1 }]
  },
  physics_drive_discharge_constraints: {
    text: "Discharge cycles impose logistical planning limits on long-range fleets. Larger vessels accumulate charge faster due to higher mass. Combat operations at sustained FTL strain cores significantly. Emergency discharge into hull structures is lethal to unshielded electronics and crew.",
    triggers: [{ word: "discharge", weight: 2 }]
  },
  physics_sensor_visibility: {
    text: "FTL vessels emit extreme energy signatures due to blueshifted radiation and drive field distortion. There are no faster-than-light sensors; detection still obeys light-speed limits. Long-range tracking relies on emission profiling and scout relays.",
    triggers: [{ word: "sensor", weight: 1 }, { word: "detection", weight: 1 }]
  },
  physics_sublight_propulsion: {
    text: "Conventional sublight propulsion uses fusion drives augmented by mass effect field reduction. In-system travel depends on reaction mass and acceleration tolerances. Mass reduction enables high-G maneuvers without crushing crew.",
    triggers: [{ word: "sublight", weight: 2 }, { word: "acceleration", weight: 1 }]
  },
  physics_artificial_gravity: {
    text: "Artificial gravity on ships and stations is generated via controlled high-mass fields projected directionally. Rotational gravity is still used in megastructures where energy efficiency or redundancy is required.",
    triggers: [{ word: "gravity", weight: 1 }]
  },
  physics_kinetic_barriers: {
    text: "Kinetic barriers use high-mass fields to increase the effective mass of incoming projectiles upon impact. Shields are tuned to specific velocity thresholds; slow-moving objects can bypass barriers. Barrier cycling requires capacitor recharge and heat management.",
    triggers: [{ word: "shield", weight: 2 }, { word: "barrier", weight: 2 }]
  },
  physics_industrial_applications: {
    text: "Low-mass fields enable precision alloy mixing and heavy construction by reducing structural stress during assembly. High-mass compression allows ultra-dense material fabrication. Eezo-dependent manufacturing creates economic chokepoints.",
    triggers: [{ word: "industry", weight: 1 }]
  },
  physics_medical_applications: {
    text: "Eezo fields are used in advanced surgery, tissue regeneration, and certain biotic enhancement drugs. Misuse or unregulated exposure increases cancer risk. Implant calibration is critical to prevent neural overload.",
    triggers: [{ word: "medical", weight: 1 }, { word: "implant", weight: 1 }]
  },
  physics_energy_limits: {
    text: "Mass effect manipulation does not create energy; it redistributes effective mass within known conservation laws. Reactor output remains the bottleneck. Large-scale field generation requires fusion or antimatter-grade power density.",
    triggers: [{ word: "reactor", weight: 1 }]
  },
  physics_field_instability: {
    text: "Field collapse events can cause gravitational shear, localized EMP effects, and structural failure. Improper synchronization between multiple emitters leads to harmonic resonance instability.",
    triggers: [{ word: "instability", weight: 1 }]
  },
  physics_strategic_dependency: {
    text: "All interstellar civilization depends on stable mass effect theory. Without Eezo access, FTL travel, shields, biotics, and artificial gravity cease to function at scale. Control of Eezo supply directly determines long-term military viability.",
    triggers: [{ word: "supply", weight: 1 }, { word: "resource", weight: 1 }]
  },
  physics_eezo_extraction_economics: {
    text: "Eezo deposits are concentrated in asteroid belts near neutron stars. Mining operations require radiation-hardened automation and extreme capital investment. Only major corporations or state-backed entities can operate viable Eezo extraction networks. Supply concentration creates long-term geopolitical leverage.",
    triggers: [{ word: "mining", weight: 1 }]
  },
  physics_corporate_control: {
    text: "Because Eezo underpins FTL, shields, and biotics, corporations controlling refining infrastructure influence military production rates. Strategic embargo or sabotage of refining facilities has disproportionate systemic impact.",
    triggers: [{ word: "corporation", weight: 1 }]
  },
  physics_drive_heat_scaling: {
    text: "FTL drive charge accumulation scales with vessel mass, velocity, and duration of sustained field projection. Dreadnought-class vessels require significantly more frequent discharge cycles than frigates during high-intensity maneuver operations.",
    triggers: [{ word: "heat", weight: 1 }]
  },
  physics_discharge_infrastructure: {
    text: "Safe discharge of drive cores requires planetary magnetospheres, gas giants, specialized Citadel facilities, or dedicated discharge platforms. Lack of discharge access restricts deep-space fleet endurance.",
    triggers: [{ word: "discharge facility", weight: 2 }]
  },
  physics_ftl_visibility_doctrine: {
    text: "FTL vessels emit extreme blueshifted radiation due to mass field distortion. Ships at FTL are highly visible across interplanetary distances, though detection remains bound by light-speed signal delay. Stealth at FTL is functionally impossible.",
    triggers: [{ word: "blueshift", weight: 1 }, { word: "stealth", weight: 1 }]
  },
  physics_no_ftl_sensors: {
    text: "No sensor technology exceeds light speed. Tactical awareness depends on scouts, relay communications, and predictive modeling. Surprise at interstellar scale is limited by detection latency.",
    triggers: [{ word: "sensor", weight: 1 }]
  },
  physics_normandy_scale_reference: {
    text: "Advanced stealth-capable drive cores (e.g., experimental Alliance designs) require massive Eezo quantities and precise field harmonics. High-end military vessels represent extreme economic concentration of mass effect resources.",
    triggers: [{ word: "normandy", weight: 2 }]
  },
  physics_biotic_nodule_risk: {
    text: "Biotics possess Eezo nodules in neural tissue. These nodules are inherently carcinogenic. Without implants to regulate output, spontaneous field discharge can cause seizures, hemorrhage, or death.",
    triggers: [{ word: "nodule", weight: 1 }]
  },
  physics_biotic_caloric_load: {
    text: "Sustained biotic use dramatically increases metabolic demand. Combat biotics require significantly elevated caloric and electrolyte intake to prevent collapse. Extended operations without supply degrade effectiveness rapidly.",
    triggers: [{ word: "calorie", weight: 1 }]
  },
  physics_l2_implant_instability: {
    text: "Early-generation human L2 biotic implants exhibited high failure rates, neural scarring, and psychological instability. Implant calibration errors can produce chronic pain syndromes or violent behavioral shifts.",
    triggers: [{ word: "l2", weight: 2 }]
  },
  physics_biotic_cultural_stigma: {
    text: "Unregulated biotics historically triggered public fear, especially in human populations. Registration laws, segregation proposals, and extremist backlash movements emerged in several systems.",
    triggers: [{ word: "stigma", weight: 1 }]
  },
  physics_red_sand_derivative: {
    text: "Red Sand and similar stimulants are derived from refined Eezo exposure compounds. Temporary enhancement of biotic output occurs at high addiction and neurological degradation risk.",
    triggers: [{ word: "red sand", weight: 2 }]
  },
  physics_reactor_dependency: {
    text: "Mass effect manipulation is constrained by reactor output. Field projection scales with available energy density. Military vessels prioritize reactor redundancy to sustain barrier cycling and drive operation simultaneously.",
    triggers: [{ word: "reactor", weight: 1 }]
  },
  physics_field_interference: {
    text: "Overlapping mass fields from multiple emitters can create interference patterns, reducing barrier efficiency or destabilizing local gravity control. Fleet formations must account for harmonic compatibility.",
    triggers: [{ word: "interference", weight: 1 }]
  },

  // === RELAY CORE ===
  relay_network_topology: {
    text: "The mass relay network forms a sparse, tree-like galactic topology. Most star clusters are connected by exactly one viable relay path. This creates long, fragile corridors linking dense hub regions separated by vast underdeveloped space.",
    triggers: [{ word: "relay", weight: 2 }]
  },
  relay_primary_vs_secondary: {
    text: "Primary relays enable long-distance paired jumps between distant galactic regions. Secondary relays provide shorter-range, multi-directional links within clusters. Primary relays are strategically critical backbone nodes; secondary relays form regional meshes.",
    triggers: [{ word: "primary relay", weight: 2 }, { word: "secondary relay", weight: 1 }]
  },
  relay_activation_restrictions: {
    text: "After the Rachni Wars, Citadel law forbade activation of unknown primary relays without confirmed destination mapping. Opening a relay blindly risks contact with hostile powers or destabilizing invasions.",
    triggers: [{ word: "activate", weight: 1 }]
  },
  relay_hub_development_pattern: {
    text: "Newly activated relay systems rapidly become infrastructure hubs. Industrial centers, shipyards, and colonies cluster around relay endpoints. Investment density drops sharply beyond relay-connected systems.",
    triggers: [{ word: "hub", weight: 1 }]
  },
  relay_chokepoint_dynamics: {
    text: "Because most clusters connect through single-path relay corridors, control of one relay can isolate entire regions. Blockading or destroying a relay node collapses military reinforcement and economic exchange downstream.",
    triggers: [{ word: "chokepoint", weight: 2 }]
  },
  relay_blockade_mechanics: {
    text: "A relay blockade prevents physical transit but does not sever communication unless comm buoys are also destroyed. Sustained blockade requires fleet presence at both relay exit vectors.",
    triggers: [{ word: "blockade", weight: 2 }]
  },
  relay_charon_example: {
    text: "Humanity’s expansion depended entirely on the Charon Relay linking Sol to Arcturus. Control of this relay is a total existential chokepoint for human civilization.",
    triggers: [{ word: "charon", weight: 2 }]
  },
  relay_attican_frontier: {
    text: "The Attican Traverse functions as a frontier boundary between Citadel space and the Terminus Systems. Relays in this region are heavily contested and militarily sensitive.",
    triggers: [{ word: "attican", weight: 2 }]
  },
  relay_citadel_core_link: {
    text: "The Citadel contains an integrated relay of unprecedented scale. This relay historically functioned as a hidden backdoor to dark space. Its control determines galaxy-wide strategic mobility.",
    triggers: [{ word: "citadel relay", weight: 2 }]
  },
  relay_mobilization_logic: {
    text: "Fleet mobilization revolves around staging at forward relay systems. Dreadnought formations must secure relay exits before advancing. Surprise assaults typically require relay infiltration or internal sabotage.",
    triggers: [{ word: "mobilize", weight: 1 }]
  },
  relay_destruction_consequences: {
    text: "Destruction of a relay risks massive system-wide devastation due to released energy discharge. Relay loss permanently removes that corridor from the network, reshaping galactic trade routes.",
    triggers: [{ word: "destroy relay", weight: 2 }]
  },
  relay_navigation_constraints: {
    text: "Ships cannot freely plot arbitrary FTL paths across interstellar void. Relay topology dictates macro-scale movement. Outside relay corridors, FTL travel becomes exponentially slower and economically unviable.",
    triggers: [{ word: "navigation", weight: 1 }]
  },
  relay_economic_dependency: {
    text: "Trade flows along stable relay corridors. Core worlds prosper due to dense relay interconnection. Frontier economies suffer from distance and limited relay adjacency.",
    triggers: [{ word: "trade route", weight: 1 }]
  },
  comm_buoy_network: {
    text: "Interstellar communication relies on chained quantum-entanglement communicators and relay-linked buoy arrays. Destroying comm buoys isolates sectors informationally even if physical transit remains possible.",
    triggers: [{ word: "comm buoy", weight: 2 }]
  },
  infrastructure_vulnerability: {
    text: "Relay nodes, comm buoys, and toll stations are high-value sabotage targets. Small-scale strikes against infrastructure can produce disproportionate economic and military disruption.",
    triggers: [{ word: "sabotage", weight: 1 }]
  },
  colonial_expansion_dependency: {
    text: "Colonization follows relay discovery. Without relay access, systems remain economically marginal. Relay discovery precedes demographic expansion.",
    triggers: [{ word: "colony", weight: 1 }]
  },
  relay_political_control: {
    text: "Political authority correlates with relay density. Council space occupies the network’s inner core. Fringe powers operate on sparse, weakly-defended outer corridors.",
    triggers: [{ word: "frontier", weight: 1 }]
  },
  relay_strategic_prediction: {
    text: "Because the relay network topology is static, strategic modeling can predict likely invasion corridors and defensive chokepoints with high reliability.",
    triggers: [{ word: "strategy", weight: 1 }]
  },
  infrastructure_economic_feedback: {
    text: "Industrial output, ship production, and military readiness scale with relay accessibility. Loss of a single high-volume relay can reduce regional GDP and fleet capacity significantly.",
    triggers: [{ word: "industry", weight: 1 }]
  },

  // === CITADEL CORE ===
  citadel_physical_scale: {
    text: "The Citadel is a Prothean-constructed megastructure approximately 44.7 kilometers in total diameter. It consists of a central Presidium ring and five massive Ward arms extending outward. The station rotates once every few minutes to generate artificial gravity along the Wards.",
    triggers: [{ word: "citadel", weight: 2 }]
  },
  citadel_gravity_distribution: {
    text: "Rotation generates near-standard gravity in the Wards while gravity decreases toward the central axis. The Presidium uses controlled mass effect fields and structural stabilization to maintain environmental consistency independent of rotation variance.",
    triggers: [{ word: "presidium", weight: 2 }]
  },
  citadel_keepers_maintenance: {
    text: "The Citadel’s infrastructure is maintained by the Keepers, an ancient bio-engineered species that instinctively repair systems. They do not communicate meaningfully with Council races and ignore most interference attempts.",
    triggers: [{ word: "keeper", weight: 2 }]
  },
  citadel_wards_structure: {
    text: "The five Wards are urban districts built along the inner surfaces of the Citadel arms. They contain residential blocks, commercial centers, industrial zones, docking ports, and transit corridors. Law enforcement presence varies by sector.",
    triggers: [{ word: "ward", weight: 2 }]
  },
  citadel_csec_authority: {
    text: "Citadel Security (C-Sec) operates as the primary law enforcement body. It handles customs, investigations, riot control, and patrol duties. Jurisdiction is limited to the station and recognized Citadel Space.",
    triggers: [{ word: "c sec", weight: 2 }] // Normalized format for c-sec
  },
  citadel_spectre_status: {
    text: "Spectres are Special Tactics and Reconnaissance agents who answer only to the Council. They operate above standard law, with authority to override local regulations in matters affecting galactic stability.",
    triggers: [{ word: "spectre", weight: 2 }]
  },
  citadel_council_structure: {
    text: "The Citadel Council is composed of representatives from the Asari, Turian, and Salarian governments. Major decisions require consensus among member races. Associate species hold embassies but lack full voting authority.",
    triggers: [{ word: "council", weight: 2 }]
  },
  citadel_conventions: {
    text: "Citadel Conventions regulate colonization rights, warfare conduct, AI prohibition, and species recognition protocols. Enforcement relies on member compliance rather than centralized coercive force.",
    triggers: [{ word: "convention", weight: 1 }]
  },
  citadel_associate_membership: {
    text: "Associate species such as humanity hold embassies and limited diplomatic privileges but cannot veto Council resolutions. Advancement to full Council status requires prolonged political alignment.",
    triggers: [{ word: "embassy", weight: 1 }]
  },
  citadel_customs_and_trade: {
    text: "All incoming and outgoing vessels are subject to customs review, cargo inspection, and weapons regulation. Trade hubs on the Citadel process high volumes of interstellar commerce daily.",
    triggers: [{ word: "trade", weight: 1 }]
  },
  citadel_defensive_capabilities: {
    text: "The Citadel possesses integrated defense systems, fleet support docks, and rapid deployment staging capacity. However, defense relies on coordinated fleet response from Council member states.",
    triggers: [{ word: "defense", weight: 1 }]
  },
  citadel_internal_politics: {
    text: "Council species maintain internal political agendas even while serving on the Council. Lobbying, diplomatic maneuvering, and bureaucratic influence campaigns are constant within Presidium chambers.",
    triggers: [{ word: "politics", weight: 1 }]
  },
  citadel_enforcement_limitations: {
    text: "C-Sec cannot enforce law outside Citadel Space. Terminus Systems operate beyond Council authority. Even within the station, manpower limitations prevent total oversight of all sectors.",
    triggers: [{ word: "terminus", weight: 1 }]
  },
  citadel_economic_centrality: {
    text: "The Citadel functions as the economic heart of Citadel Space. Financial institutions, trade brokers, and corporate headquarters cluster within its districts. Market fluctuations on the station ripple across the galaxy.",
    triggers: [{ word: "economy", weight: 1 }]
  },
  citadel_transit_systems: {
    text: "Mass transit within the Citadel includes rapid rail systems, shuttle corridors, and docking platforms integrated into Ward arms. Internal mobility infrastructure is essential to maintain operational stability.",
    triggers: [{ word: "transit", weight: 1 }]
  },
  citadel_energy_grid: {
    text: "The Citadel operates on a massive integrated power grid sustained by fusion reactors and mass effect stabilization cores. Power disruption in one Ward can cascade into adjacent systems if not isolated quickly.",
    triggers: [{ word: "power", weight: 1 }]
  },
  citadel_symbolic_authority: {
    text: "Beyond its physical and political functions, the Citadel symbolizes galactic unity and Council legitimacy. Control of the station confers immense psychological and diplomatic leverage.",
    triggers: [{ word: "unity", weight: 1 }]
  },
  citadel_security_fragility: {
    text: "Despite advanced systems, infiltration risks remain. Spectre misconduct, political corruption, and internal sabotage have historically exposed structural vulnerabilities within the station’s governance.",
    triggers: [{ word: "corruption", weight: 1 }]
  },

  // === COMMUNICATION CORE ===
  comm_qec_foundations: {
    text: "Quantum Entanglement Communication (QEC) enables instantaneous data transmission between paired entangled particles. Each QEC link requires a physically paired quantum device; new links cannot be created remotely. QEC capacity is limited, expensive, and strategically scarce.",
    triggers: [{ word: "qec", weight: 2 }, { word: "entanglement", weight: 1 }]
  },
  comm_extranet_structure: {
    text: "The extranet functions as the galaxy-wide data network, linking planets and stations through relay-linked comm buoys and high-capacity transmission arrays. Unlike QEC, extranet data travels at light speed and experiences relay latency.",
    triggers: [{ word: "extranet", weight: 2 }]
  },
  comm_latency_constraints: {
    text: "Even with relay-linked routing, extranet communication obeys relativistic limits. Interstellar messages may require hours or days depending on distance and relay density. Real-time coordination across the galaxy is impossible without QEC.",
    triggers: [{ word: "latency", weight: 1 }]
  },
  comm_military_priority_channels: {
    text: "Military forces reserve QEC channels for high-command directives, fleet coordination, and strategic alerts. Civilian QEC usage is minimal due to cost and regulatory control.",
    triggers: [{ word: "military channel", weight: 1 }]
  },
  comm_data_encryption_asymmetry: {
    text: "Advanced encryption protocols protect Council and corporate networks. Frontier systems often lack comparable cryptographic infrastructure, making them vulnerable to interception and espionage.",
    triggers: [{ word: "encryption", weight: 1 }]
  },
  comm_information_warfare: {
    text: "Control of communication channels enables narrative dominance. Governments and corporations shape public perception through extranet influence campaigns, data suppression, and strategic leaks.",
    triggers: [{ word: "propaganda", weight: 1 }, { word: "narrative", weight: 1 }]
  },
  comm_censorship_mechanics: {
    text: "Citadel authorities can restrict extranet access within their jurisdiction during emergencies. However, Terminus regions operate independent networks beyond Council censorship reach.",
    triggers: [{ word: "censorship", weight: 1 }]
  },
  comm_media_fragmentation: {
    text: "Media ecosystems differ between core and frontier regions. Core worlds rely on regulated corporate broadcasters, while frontier systems depend on decentralized or pirate transmission hubs.",
    triggers: [{ word: "media", weight: 1 }]
  },
  comm_surveillance_capacity: {
    text: "C-Sec and Council intelligence services monitor extranet traffic for threat indicators. Full-spectrum surveillance is limited by bandwidth, encryption, and legal constraints.",
    triggers: [{ word: "surveillance", weight: 1 }]
  },
  comm_intelligence_agencies: {
    text: "Each Council species maintains its own intelligence apparatus layered over Citadel structures. Information sharing occurs selectively and is influenced by political trust levels.",
    triggers: [{ word: "intelligence", weight: 1 }]
  },
  comm_data_center_nodes: {
    text: "Major relay hubs contain data-processing centers responsible for routing extranet traffic. These nodes are hardened targets in wartime due to their strategic informational importance.",
    triggers: [{ word: "data center", weight: 1 }]
  },
  comm_cybersecurity_vulnerability: {
    text: "Cyberattacks targeting infrastructure nodes can disrupt trade, banking, fleet coordination, and emergency response systems. Digital warfare precedes physical engagement in most conflicts.",
    triggers: [{ word: "cyber", weight: 1 }]
  },
  comm_trade_dependency: {
    text: "Modern galactic commerce relies on continuous extranet access for credit transfer, market pricing, and logistics coordination. Network outage rapidly destabilizes regional economies.",
    triggers: [{ word: "credit transfer", weight: 1 }]
  },
  comm_political_leverage: {
    text: "States with superior encryption, bandwidth control, and QEC access possess disproportionate diplomatic leverage. Information asymmetry shapes negotiation outcomes.",
    triggers: [{ word: "negotiation", weight: 1 }]
  },
  comm_crisis_response_latency: {
    text: "During large-scale emergencies, information bottlenecks delay fleet mobilization and civilian evacuation. QEC saturation can occur if too many priority channels activate simultaneously.",
    triggers: [{ word: "emergency", weight: 1 }]
  },
  comm_extranet_regulation: {
    text: "Citadel Space enforces standards on data routing, AI filtering, and broadcast licensing. Frontier and Terminus systems often bypass these standards, creating legal gray zones.",
    triggers: [{ word: "regulation", weight: 1 }]
  },
  comm_black_market_networks: {
    text: "Illegal data exchanges operate through encrypted shadow networks. Pirate groups and mercenary organizations use private relay taps and spoofed buoy identifiers to conceal traffic.",
    triggers: [{ word: "black market", weight: 1 }]
  },

  // === AI CORE ===
  ai_definition_distinction: {
    text: "Citadel law distinguishes between Virtual Intelligences (VIs) and true Artificial Intelligences (AIs). VIs simulate adaptive behavior but lack self-awareness or independent goal formation. True AIs possess recursive self-improvement capability and autonomous cognition.",
    triggers: [{ word: "ai", weight: 2 }, { word: "artificial intelligence", weight: 2 }]
  },
  ai_blue_box_architecture: {
    text: "True AIs require specialized quantum computing cores often referred to as 'blue boxes.' These systems enable adaptive learning beyond static programming constraints. Construction of such systems is strictly regulated and effectively banned in Citadel Space.",
    triggers: [{ word: "blue box", weight: 2 }]
  },
  ai_citadel_prohibition: {
    text: "Following historical synthetic uprisings, Citadel Conventions explicitly prohibit the creation, importation, or experimentation with self-aware AI systems. Violation constitutes a galactic-level criminal offense.",
    triggers: [{ word: "ban", weight: 1 }, { word: "prohibited", weight: 1 }]
  },
  ai_geth_precedent: {
    text: "The Geth originated as networked labor platforms created by the Quarians. Emergent self-awareness triggered conflict, resulting in the Quarian exile. This event serves as the primary legal and cultural justification for AI prohibition.",
    triggers: [{ word: "geth", weight: 2 }]
  },
  ai_vi_permitted_scope: {
    text: "Virtual Intelligences are permitted for commercial, navigational, medical, and administrative use. VIs may simulate personality and decision trees but are legally restricted from recursive self-modification or unsupervised autonomy.",
    triggers: [{ word: "vi", weight: 2 }]
  },
  ai_military_vi_usage: {
    text: "Military forces deploy advanced VIs for targeting assistance, logistics modeling, and threat analysis. These systems operate within constrained behavioral parameters and are intentionally prevented from independent strategic control.",
    triggers: [{ word: "military ai", weight: 1 }]
  },
  ai_research_surveillance: {
    text: "Council intelligence agencies actively monitor research institutions for illegal AI development. Quantum core imports, anomalous processing clusters, and unauthorized heuristic expansion trigger investigation.",
    triggers: [{ word: "research", weight: 1 }]
  },
  ai_black_market_development: {
    text: "Despite prohibition, underground research cells attempt AI construction in Terminus regions and corporate black labs. Such systems are unstable and frequently lack ethical constraint frameworks.",
    triggers: [{ word: "black market", weight: 1 }]
  },
  ai_political_crisis_trigger: {
    text: "Discovery of an active self-aware AI within Citadel jurisdiction triggers immediate Council-level emergency response. Military intervention and sanctions are standard protocol.",
    triggers: [{ word: "crisis", weight: 1 }]
  },
  ai_synthetic_rights_debate: {
    text: "Philosophical debate exists regarding synthetic personhood. While officially banned, some fringe academic circles argue for limited AI rights recognition. These discussions remain politically suppressed.",
    triggers: [{ word: "rights", weight: 1 }]
  },
  ai_cultural_fear_memory: {
    text: "Public opinion across most species associates AI with existential threat. The memory of synthetic rebellions shapes education, media narratives, and policy reflexes.",
    triggers: [{ word: "fear", weight: 1 }]
  },
  ai_indoctrination_risk: {
    text: "Advanced synthetic systems are vulnerable to hostile signal corruption or external control if improperly isolated. Historical cases demonstrate that networked AIs can be subverted by superior signal architectures.",
    triggers: [{ word: "corruption", weight: 1 }]
  },
  ai_network_scaling_risk: {
    text: "AI capability scales exponentially with networked processing nodes. Distributed synthetic consciousness increases strategic unpredictability and resistance to containment.",
    triggers: [{ word: "network", weight: 1 }]
  },
  ai_quarian_legacy: {
    text: "Quarian exile culture remains shaped by their creation of the Geth. Synthetic research among Quarians is politically sensitive and tightly controlled.",
    triggers: [{ word: "quarian", weight: 1 }]
  },
  ai_corporate_constraint: {
    text: "Major corporations publicly comply with AI bans but invest heavily in high-tier VI systems approaching legal boundaries. The distinction between advanced VI and proto-AI is often intentionally blurred.",
    triggers: [{ word: "corporation", weight: 1 }]
  },
  ai_warfare_escalation_factor: {
    text: "Introduction of a true AI into active warfare would destabilize military equilibrium. Autonomous strategic decision loops outpace organic command latency, potentially rendering conventional doctrine obsolete.",
    triggers: [{ word: "autonomous warfare", weight: 1 }]
  },
  ai_detection_protocols: {
    text: "Council detection protocols rely on processing pattern analysis, recursive code auditing, and quantum signature scanning to identify emergent AI behavior.",
    triggers: [{ word: "detection", weight: 1 }]
  },
  ai_legal_enforcement_limits: {
    text: "Citadel enforcement cannot fully prevent AI experimentation in Terminus space or isolated frontier systems. Legal jurisdiction weakens beyond core relay density.",
    triggers: [{ word: "frontier", weight: 1 }]
  },
  ai_synthetic_integration_edgecase: {
    text: "Hybrid integration of synthetic and organic systems (cybernetic augmentation approaching AI autonomy) exists in a regulatory gray zone. Oversight committees debate thresholds for classification.",
    triggers: [{ word: "hybrid", weight: 1 }]
  },
  ai_strategic_instability_model: {
    text: "AI emergence represents a systemic instability variable. If a self-aware synthetic network gains relay access and manufacturing capacity, containment probability decreases sharply.",
    triggers: [{ word: "instability", weight: 1 }]
  },

  // === ECONOMY CORE ===
  econ_credit_standard: {
    text: "The galactic credit is a unified digital currency regulated through Citadel banking institutions. Credit balances exist primarily as encrypted extranet records rather than physical tender. Stability depends on continuous network uptime.",
    triggers: [{ word: "credit", weight: 2 }]
  },
  econ_banking_houses: {
    text: "Major interstellar banking houses operate across multiple relay-connected hubs. These institutions provide interspecies credit clearing, war bond issuance, and industrial financing. Their solvency is systemically critical.",
    triggers: [{ word: "bank", weight: 1 }]
  },
  econ_tariffs_and_sanctions: {
    text: "The Citadel Council may impose trade sanctions, tariffs, or embargoes against member or associate species. Enforcement relies on relay corridor monitoring and customs interdiction.",
    triggers: [{ word: "sanction", weight: 1 }, { word: "embargo", weight: 1 }]
  },
  econ_eezo_supply_chain: {
    text: "Eezo extraction, refinement, and distribution form the backbone of industrial and military production. Supply disruption rapidly impacts shipbuilding, barrier production, and biotic training infrastructure.",
    triggers: [{ word: "eezo trade", weight: 2 }]
  },
  econ_industrial_planets: {
    text: "Certain planets specialize in heavy manufacturing, shipyard construction, or high-tech component fabrication. Loss or blockade of an industrial world has cascading production effects across fleets.",
    triggers: [{ word: "shipyard", weight: 1 }]
  },
  econ_core_vs_frontier: {
    text: "Core worlds possess diversified economies and financial resilience. Frontier systems depend on narrow exports (ore, agriculture, mercenary labor) and are highly vulnerable to market fluctuation.",
    triggers: [{ word: "frontier", weight: 1 }]
  },
  econ_trade_corridor_density: {
    text: "Trade flows concentrate along high-traffic relay corridors. Corridor density correlates with GDP concentration, infrastructure investment, and political influence.",
    triggers: [{ word: "trade corridor", weight: 1 }]
  },
  econ_shipping_fleets: {
    text: "Civilian shipping fleets transport bulk materials, consumer goods, and military supplies. Shipping insurance markets reflect piracy risk, relay instability, and frontier volatility.",
    triggers: [{ word: "shipping", weight: 1 }]
  },
  econ_piracy_impact: {
    text: "Pirate raids targeting cargo vessels disrupt local supply chains and increase insurance premiums. Sustained piracy can destabilize frontier economies and shift trade routes.",
    triggers: [{ word: "piracy", weight: 1 }]
  },
  econ_corporate_power_blocs: {
    text: "Mega-corporations influence planetary governments through capital leverage, lobbying, and supply chain control. Some corporations operate de facto sovereign territories in fringe systems.",
    triggers: [{ word: "corporation", weight: 1 }]
  },
  econ_stock_market_interconnectivity: {
    text: "Interstellar stock exchanges are relay-linked and react to political or military developments in near-real time within latency constraints. Market crashes can propagate across multiple sectors.",
    triggers: [{ word: "stock", weight: 1 }]
  },
  econ_financial_contagion: {
    text: "Bank failures or industrial collapse in one system can trigger cascading insolvency through credit exposure chains. Interstellar debt obligations bind distant economies together.",
    triggers: [{ word: "collapse", weight: 1 }]
  },
  econ_labor_mobility: {
    text: "Labor migration flows follow economic opportunity along relay-connected systems. Frontier labor shortages and core overqualification produce demographic imbalance.",
    triggers: [{ word: "labor", weight: 1 }]
  },
  econ_automation_dependency: {
    text: "Advanced automation and VI-managed logistics dominate core world economies. Frontier systems rely more heavily on manual or semi-automated labor structures.",
    triggers: [{ word: "automation", weight: 1 }]
  },
  econ_war_industrial_pivot: {
    text: "During large-scale conflict, industrial output pivots toward military production. Civilian manufacturing contracts while shipyards and weapons facilities expand capacity.",
    triggers: [{ word: "war economy", weight: 1 }]
  },
  econ_resource_stratification: {
    text: "Certain resources (Eezo, rare metals, element isotopes) create stratified wealth distribution between systems. Resource monopolies can sustain long-term geopolitical leverage.",
    triggers: [{ word: "resource", weight: 1 }]
  },
  econ_trade_regulation_variance: {
    text: "Citadel Space enforces regulatory compliance in trade safety, AI usage, and tariff alignment. Terminus and fringe systems operate under looser or nonexistent regulatory oversight.",
    triggers: [{ word: "regulation", weight: 1 }]
  },
  econ_black_market_trade: {
    text: "Illicit trade networks exchange restricted technology, AI components, weapons, and biotic enhancers. These networks operate through relay-adjacent shadow ports.",
    triggers: [{ word: "black market", weight: 1 }]
  },
  econ_credit_manipulation: {
    text: "Interest rate shifts, liquidity tightening, and credit withdrawal are tools used by powerful financial houses to discipline weaker economies or influence policy outcomes.",
    triggers: [{ word: "interest rate", weight: 1 }]
  },
  econ_relay_blockade_economic_effect: {
    text: "Blockading a major relay corridor halts imports and exports, forcing local rationing and industrial slowdown. Extended blockade reduces GDP, military readiness, and civilian stability.",
    triggers: [{ word: "blockade", weight: 1 }]
  },
  econ_population_support_capacity: {
    text: "Population stability depends on reliable import of food, medicine, and consumer goods through relay trade. Disruption increases civil unrest probability.",
    triggers: [{ word: "unrest", weight: 1 }]
  },
  econ_infrastructure_investment_cycle: {
    text: "Wealthier systems reinvest surplus capital into shipyards, research institutions, and defensive platforms. Economic strength feeds back into strategic resilience.",
    triggers: [{ word: "investment", weight: 1 }]
  },
  econ_debt_diplomacy: {
    text: "Weaker states may exchange political concessions for financial rescue packages from stronger powers or corporate syndicates. Debt diplomacy alters alliance structures.",
    triggers: [{ word: "debt", weight: 1 }]
  },
  econ_crisis_exploitation: {
    text: "Economic crises create acquisition opportunities for dominant corporations and states. Strategic buyouts during collapse consolidate long-term control over production assets.",
    triggers: [{ word: "acquisition", weight: 1 }]
  },
  econ_insurance_and_risk_modeling: {
    text: "Shipping, industrial output, and planetary stability are quantified in actuarial risk models. Rising risk premiums signal systemic instability before military conflict begins.",
    triggers: [{ word: "insurance", weight: 1 }]
  }
};


// ---------- UTILITY FUNCTIONS ----------

// Strip punctuation safely to prevent matching errors (e.g. "eezo?" or "c-sec")
function normalizeText(s) {
  s = String(s || "").toLowerCase();
  s = s.replace(/[^a-z0-9_\s-]/g, " "); // Replaces punctuation with spaces
  s = s.replace(/[-_]+/g, " ");        // Treats hyphens/underscores as spaces
  s = s.replace(/\s+/g, " ").trim();   // Collapses multiple spaces
  return s;
}


// ---------- MESSAGE WINDOW GATHERING ----------

var WINDOW_DEPTH = 4;
var lm = context.chat.last_messages;
var combinedRaw = "";

if (lm && lm.length > 0) {
  var start = Math.max(0, lm.length - WINDOW_DEPTH);
  for (var i = start; i < lm.length; i++) {
    var msg = lm[i].message || lm[i];
    combinedRaw += " " + msg;
  }
} else {
  combinedRaw = context.chat.last_message || "";
}

// Apply normalization and padding for foolproof `.indexOf` matching
var combined = " " + normalizeText(combinedRaw) + " ";


// ---------- DYNAMIC SCORING ENGINE ----------

var score = {};

// Loop through the Data-Driven WORLD object
for (var key in WORLD) {
  if (WORLD.hasOwnProperty(key)) {
    var entry = WORLD[key];
    score[key] = 0; // Initialize score safely

    // Loop through triggers for this specific lore piece
    for (var j = 0; j < entry.triggers.length; j++) {
      var trigger = entry.triggers[j];
      
      // If the word is found, add the weight to the score
      if (combined.indexOf(" " + trigger.word + " ") !== -1) {
        score[key] += trigger.weight;
      }
    }
  }
}


// ---------- SORTING & SCENARIO INJECTION ----------

var selected = [];

// Filter out entries with 0 score
for (var k in score) {
  if (score.hasOwnProperty(k) && score[k] > 0) {
    selected.push(k);
  }
}

// Sort the selected array by score (Highest score first)
selected.sort(function(a, b) {
  return score[b] - score[a];
});

var MAX_MODULES = 5;

// Apply the text of the top-scoring modules to the character's scenario
for (var n = 0; n < selected.length && n < MAX_MODULES; n++) {
  var winningKey = selected[n];
  context.character.scenario += "\n\n" + WORLD[winningKey].text;
}
